<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $title }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', sans-serif; font-size: 12px; color: #1a1a2e; }
        .page { padding: 30px 40px; }
        .header { display: flex; justify-content: space-between; border-bottom: 3px solid #1F4E79; padding-bottom: 16px; margin-bottom: 24px; }
        .company-name { font-size: 20px; font-weight: bold; color: #1F4E79; }
        .doc-title { font-size: 14px; color: #555; margin-top: 4px; }
        .meta-box { text-align: right; font-size: 11px; color: #666; line-height: 1.6; }
        .section-title { font-size: 13px; font-weight: bold; color: #1F4E79; border-bottom: 1px solid #ddd; padding-bottom: 6px; margin-bottom: 12px; }
        table { width: 100%; border-collapse: collapse; }
        th { background: #1F4E79; color: #fff; padding: 8px 10px; text-align: left; font-size: 11px; }
        td { padding: 7px 10px; border-bottom: 1px solid #eee; font-size: 11px; }
        tr:nth-child(even) td { background: #f8f9fa; }
        .label { font-weight: bold; color: #444; width: 35%; }
        .footer { margin-top: 40px; border-top: 1px solid #ddd; padding-top: 12px; text-align: center; font-size: 10px; color: #999; }
    </style>
</head>
<body>
    <div class="page">
        <div class="header">
            <div>
                <div class="company-name">ERP System</div>
                <div class="doc-title">{{ $title }}</div>
            </div>
            <div class="meta-box">
                <div>Date: {{ now()->format('d F Y') }}</div>
                <div>Generated by: {{ auth()->user()->name ?? 'System' }}</div>
            </div>
        </div>
        <div class="section-title">Detail Information</div>
        @php $data = is_object($entity) && method_exists($entity, 'toArray') ? $entity->toArray() : (array) $entity; @endphp
        <table>
            <tr><td class="label">ID</td><td>{{ $data['id'] ?? '-' }}</td></tr>
            <tr><td class="label">Name</td><td>{{ $data['name'] ?? '-' }}</td></tr>
            {{-- TODO: add entity-specific fields here --}}
            <tr><td class="label">Created At</td><td>{{ $data['created_at'] ?? '-' }}</td></tr>
            <tr><td class="label">Updated At</td><td>{{ $data['updated_at'] ?? '-' }}</td></tr>
        </table>
        <div class="footer">
            <p>ERP System &mdash; Generated on {{ now()->format('d/m/Y H:i:s') }}</p>
        </div>
    </div>
</body>
</html>
